version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

defaults: &defaults
  docker:
    - image: cimg/node:20.10-browsers
  working_directory: ~/puppeteer-devtools

commands:
  install_chrome:
    parameters:
      chrome-version:
        type: string
        default: "latest"
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: << parameters.chrome-version >>
      - run:
          command: |
            google-chrome --version
          name: Google Chrome Version

npm_cache_key: &npm_cache_key
  v2-node-modules-cache-{{ checksum "package-lock.json" }}

restore_node_modules_cache: &restore_node_modules_cache
  restore_cache:
    keys:
      - *npm_cache_key
      - v2-node-modules-cache-

npm_auth: &npm_auth
  run:
    name: npm auth
    command: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      # Skip the bundled version of chrome; always use the one provided from circle
      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
      - save_cache:
          paths:
            - node_modules
          key: *npm_cache_key
  test:
    <<: *defaults
    parameters:
      chrome-version:
        type: string
    steps:
      - install_chrome:
          chrome-version: << parameters.chrome-version >>
      - checkout
      - <<: *restore_node_modules_cache
      - run: PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome npm run coverage
  lint:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - run: npm run lint
  release_next:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - <<: *npm_auth
      # Tag develop commits with commit hash and push out with next tag
      - run: npm version "$(node -p 'require("./package.json").version')-next-${CIRCLE_SHA1:0:8}" --no-git-tag-version
      - run: npm publish --tag next
  release:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - <<: *npm_auth
      - run: npm publish

workflows:
  build:
    jobs:
      - dependencies
      - test:
          matrix:
            parameters:
              chrome-version: ["latest", "102.0.5002.0"]
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - release:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
      - release_next:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - develop

